module.exports = {
    FILES_UPLOAD: 'FILES_UPLOAD',
    RUN_FOCUSSED_SLIDE: 'RUN_FOCUSSED_SLIDE',
    FOCUS_CURRENT_EDITOR: 'FOCUS_CURRENT_EDITOR',
    LEAVE_CURRENT_EDITOR: 'LEAVE_CURRENT_EDITOR'
};
